### ISSUE TITLE
crewmembers wont attack enemies.

### ISSUE THREAD

**Issue by Nox-Echo** [Avali-Triage-Team/Avali#306] opened 2016-08-23 02:05 UTC
loaded the game then exited it.
for some reason my crew members refuse to attack hostiles
they follow me and do everything else as intended but they WILL NOT attack.

[spoiler][21:00:38.256] [Info] Root: Preparing Root...
[21:00:38.257] [Info] Root: Done preparing Root.
[21:00:38.257] [Info] Client Version 1.0.5 (windows x86_64) Source ID: 7d4a2bbba04d43bd7f43f0ca940db23b2187edc1 Protocol: 724
[21:00:38.257] [Info] Root: Scanning for asset sources in directory '..\assets\'
[21:00:38.488] [Info] Root: Scanning for asset sources in directory '..\mods\'
[21:00:38.514] [Info] Root: Detected asset source named 'base' at '..\assets\packed.pak'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\assets\mags'
[21:00:38.514] [Info] Root: Detected asset source named '^#7500a0;A^#8d02ad;u^#a504ba;r^#7500a0;o^#8d02ad;r^#a504ba;a^reset;'s SB 1.0 Mod' at '..\mods\AuroraBorealis1.0Mod-ILB'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\mods\Godbikes'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\mods\JetSpear'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\mods\Nox's Tracks'
[21:00:38.514] [Info] Root: Detected asset source named 'Targeted Blink' at '..\mods\TargetedBlink'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\mods\defaultinstruments'
[21:00:38.514] [Info] Root: Detected unnamed asset source at '..\assets\user'
[21:00:38.514] [Info] Loading assets from: '..\assets\packed.pak'
[21:00:38.802] [Info] Loading assets from: '..\assets\mags'
[21:00:38.802] [Info] Loading assets from: '..\mods\AuroraBorealis1.0Mod-ILB'
[21:00:38.804] [Info] Loading assets from: '..\mods\Godbikes'
[21:00:38.805] [Info] Loading assets from: '..\mods\JetSpear'
[21:00:38.806] [Info] Loading assets from: '..\mods\Nox's Tracks'
[21:00:38.879] [Info] Loading assets from: '..\mods\TargetedBlink'
[21:00:38.880] [Info] Loading assets from: '..\mods\defaultinstruments'
[21:00:38.894] [Info] Loading assets from: '..\assets\user'
[21:00:39.562] [Info] Assets digest is 575307884e3f8cda0fe60e8a2b4d9d3c942d2a0ae9bde329668aec33834346be
[21:00:39.562] [Info] Root: Loaded Assets in 1.30505 seconds
[21:00:39.565] [Info] Application: Initializing SDL Video
[21:00:39.567] [Info] Application: Initializing SDL Joystick
[21:00:39.688] [Info] Application: Initializing SDL Sound
[21:00:39.798] [Info] Initialized Steam services
[21:00:39.799] [Info] Application: Creating SDL Window
[21:00:39.920] [Info] Application: Enabling VSync with late swap tearing
[21:00:39.996] [Info] Application: Opened default audio device with 44.1khz / 16 bit stereo audio, 2048 sample size buffer
[21:00:40.003] [Info] OpenGL version: '4.5.0 NVIDIA 368.22' vendor: 'NVIDIA Corporation' renderer: 'GeForce GTX 960/PCIe/SSE2' shader: '4.50 NVIDIA'
[21:00:40.006] [Info] Application: initialization...
[21:00:40.006] [Info] Root: Loaded Configuration in 0.000833471 seconds
[21:00:40.008] [Info] Application: renderer initialization...
[21:00:40.010] [Info] Root: Loaded ImageMetadataDatabase in 4.03391e-06 seconds
[21:00:40.022] [Info] Application: main update loop...
[21:00:40.024] [Info] Loading mods from user generated content with id '729427264' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427264'
[21:00:40.024] [Info] Loading mods from user generated content with id '729754278' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729754278'
[21:00:40.024] [Info] Loading mods from user generated content with id '731836919' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\731836919'
[21:00:40.024] [Info] Loading mods from user generated content with id '729427744' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427744'
[21:00:40.025] [Info] Loading mods from user generated content with id '729558042' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729558042'
[21:00:40.025] [Info] Loading mods from user generated content with id '729426722' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729426722'
[21:00:40.025] [Info] Loading mods from user generated content with id '741491949' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\741491949'
[21:00:40.025] [Info] Loading mods from user generated content with id '730684624' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730684624'
[21:00:40.025] [Info] Loading mods from user generated content with id '730686715' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730686715'
[21:00:40.025] [Info] Loading mods from user generated content with id '729492703' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492703'
[21:00:40.025] [Info] Loading mods from user generated content with id '729492334' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492334'
[21:00:40.026] [Info] Loading mods from user generated content with id '729480149' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729480149'
[21:00:40.026] [Info] Loading mods from user generated content with id '729731551' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729731551'
[21:00:40.026] [Info] Loading mods from user generated content with id '745422579' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\745422579'
[21:00:40.026] [Info] Loading mods from user generated content with id '749696943' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\749696943'
[21:00:40.026] [Info] Loading mods from user generated content with id '733139672' from directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\733139672'
[21:00:40.026] [Info] Reloading to include all user generated content
[21:00:40.026] [Info] Root: Reloading from disk
[21:00:40.026] [Info] Root: Writing runtime configuration to '..\storage\starbound.config'
[21:00:40.048] [Info] Root: Loaded Configuration in 0.00087381 seconds
[21:00:40.049] [Info] Root: Scanning for asset sources in directory '..\assets\'
[21:00:40.264] [Info] Root: Scanning for asset sources in directory '..\mods\'
[21:00:40.286] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427264'
[21:00:40.287] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729754278'
[21:00:40.288] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\731836919'
[21:00:40.335] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427744'
[21:00:40.341] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729558042'
[21:00:40.351] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729426722'
[21:00:40.351] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\741491949'
[21:00:40.352] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730684624'
[21:00:40.352] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730686715'
[21:00:40.352] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492703'
[21:00:40.354] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492334'
[21:00:40.357] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729480149'
[21:00:40.435] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729731551'
[21:00:40.436] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\745422579'
[21:00:40.436] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\749696943'
[21:00:40.437] [Info] Root: Scanning for asset sources in directory 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\733139672'
[21:00:40.437] [Info] Root: Detected asset source named 'base' at '..\assets\packed.pak'
[21:00:40.437] [Info] Root: Detected asset source named 'xbawks' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729426722\contents.pak'
[21:00:40.437] [Info] Root: Detected unnamed asset source at '..\assets\mags'
[21:00:40.437] [Info] Root: Detected asset source named '^#7500a0;A^#8d02ad;u^#a504ba;r^#7500a0;o^#8d02ad;r^#a504ba;a^reset;'s SB 1.0 Mod' at '..\mods\AuroraBorealis1.0Mod-ILB'
[21:00:40.437] [Info] Root: Detected unnamed asset source at '..\mods\Godbikes'
[21:00:40.437] [Info] Root: Detected unnamed asset source at '..\mods\JetSpear'
[21:00:40.437] [Info] Root: Detected unnamed asset source at '..\mods\Nox's Tracks'
[21:00:40.437] [Info] Root: Detected asset source named 'Targeted Blink' at '..\mods\TargetedBlink'
[21:00:40.437] [Info] Root: Detected unnamed asset source at '..\mods\defaultinstruments'
[21:00:40.437] [Info] Root: Detected asset source named 'Extended Songbook' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427264\contents.pak'
[21:00:40.437] [Info] Root: Detected asset source named 'Undertale Music Pack' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729754278\contents.pak'
[21:00:40.437] [Info] Root: Detected asset source named 'Super Song Pack' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\731836919\contents.pak'
[21:00:40.437] [Info] Root: Detected asset source named 'FrackinUniverse' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729480149\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Avali' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729558042\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Weapon Fusion Station' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\741491949\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'TrueSpace' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730684624\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'TrueSpaceFUSubmod' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730686715\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'FrackinMusic' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492703\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'FrackinRaces' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492334\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Phase Shift Module v1.32' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729731551\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Final Fantasy Music Addidtion [Soundtrack]' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\745422579\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Crazy Magnorbs' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\749696943\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Earth's Finest - Crew Improvements' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\733139672\contents.pak'
[21:00:40.438] [Info] Root: Detected asset source named 'Instant Crafting' at 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427744\contents.pak'
[21:00:40.438] [Info] Root: Detected unnamed asset source at '..\assets\user'
[21:00:40.438] [Info] Loading assets from: '..\assets\packed.pak'
[21:00:40.719] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729426722\contents.pak'
[21:00:40.719] [Info] Loading assets from: '..\assets\mags'
[21:00:40.720] [Info] Loading assets from: '..\mods\AuroraBorealis1.0Mod-ILB'
[21:00:40.721] [Info] Loading assets from: '..\mods\Godbikes'
[21:00:40.722] [Info] Loading assets from: '..\mods\JetSpear'
[21:00:40.723] [Info] Loading assets from: '..\mods\Nox's Tracks'
[21:00:40.797] [Info] Loading assets from: '..\mods\TargetedBlink'
[21:00:40.798] [Info] Loading assets from: '..\mods\defaultinstruments'
[21:00:40.812] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427264\contents.pak'
[21:00:40.812] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729754278\contents.pak'
[21:00:40.814] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\731836919\contents.pak'
[21:00:40.870] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729480149\contents.pak'
[21:00:40.992] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729558042\contents.pak'
[21:00:41.005] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\741491949\contents.pak'
[21:00:41.006] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730684624\contents.pak'
[21:00:41.007] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\730686715\contents.pak'
[21:00:41.007] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492703\contents.pak'
[21:00:41.009] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729492334\contents.pak'
[21:00:41.013] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729731551\contents.pak'
[21:00:41.014] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\745422579\contents.pak'
[21:00:41.015] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\749696943\contents.pak'
[21:00:41.015] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\733139672\contents.pak'
[21:00:41.015] [Info] Loading assets from: 'C:\Program Files (x86)\Steam\steamapps\workshop\content\211820\729427744\contents.pak'
[21:00:41.026] [Info] Loading assets from: '..\assets\user'
[21:00:42.089] [Info] Assets digest is 85ab85dbda05e32a3448cdf12aa3c19a9b578b1583dd2366715be3ff2d9055c6
[21:00:42.089] [Info] Root: Loaded Assets in 2.03987 seconds
[21:00:42.091] [Info] Root: Loaded ImageMetadataDatabase in 5.58537e-06 seconds
[21:00:42.092] [Info] Root: Loaded NameGenerator in 0.00324234 seconds
[21:00:42.102] [Error] OpenGL errors this frame:  GL_INVALID_VALUE
[21:00:42.146] [Info] Root: Loaded PlantDatabase in 0.053416 seconds
[21:00:42.364] [Info] Root: Loaded ObjectDatabase in 0.27503 seconds
[21:00:42.514] [Info] Root: Loaded MonsterDatabase in 0.149216 seconds
[21:00:42.553] [Info] Root: Loaded NpcDatabase in 0.039054 seconds
[21:00:42.553] [Info] Root: Loaded StagehandDatabase in 0.00041146 seconds
[21:00:42.555] [Info] Root: Loaded VehicleDatabase in 0.00228661 seconds
[21:00:42.564] [Info] Root: Loaded PlayerFactory in 0.00832106 seconds
[21:00:42.602] [Info] Root: Loaded ProjectileDatabase in 0.456116 seconds
[21:00:42.602] [Info] Root: Loaded VersioningDatabase in 0.000490587 seconds
[21:00:42.602] [Info] Root: Loaded EntityFactory in 0.038869 seconds
[21:00:42.628] [Info] Root: Loaded ParticleDatabase in 0.0254491 seconds
[21:00:42.935] [Info] Root: Loaded MaterialDatabase in 0.332491 seconds
[21:00:42.939] [Info] Root: Loaded TerrainDatabase in 0.00356785 seconds
[21:00:43.054] [Info] Root: Loaded BiomeDatabase in 0.115511 seconds
[21:00:43.056] [Info] Root: Loaded LiquidsDatabase in 0.00161729 seconds
[21:00:43.066] [Info] Root: Loaded StatusEffectDatabase in 0.0105518 seconds
[21:00:43.149] [Info] Root: Loaded DamageDatabase in 0.082365 seconds
[21:00:43.152] [Info] Root: Loaded EffectSourceDatabase in 0.00306454 seconds
[21:00:43.167] [Info] Root: Loaded FunctionDatabase in 0.0157162 seconds
[21:00:43.203] [Info] Root: Loaded TreasureDatabase in 0.0346101 seconds
[21:00:43.559] [Info] Root: Loaded DungeonDefinitions in 0.356462 seconds
[21:00:43.559] [Info] Root: Loaded TilesetDatabase in 1.86181e-05 seconds
[21:00:43.560] [Info] Root: Loaded StatisticsDatabase in 0.00119125 seconds
[21:00:43.560] [Info] Root: Loaded EmoteProcessor in 4.80968e-05 seconds
[21:00:43.565] [Info] Root: Loaded SpeciesDatabase in 0.00453661 seconds
[21:00:43.576] [Info] Root: Loaded QuestTemplateDatabase in 0.0109425 seconds
[21:00:43.577] [Info] Root: Loaded AiDatabase in 0.00111119 seconds
[21:00:43.578] [Info] Root: Loaded TechDatabase in 0.00139822 seconds
[21:00:43.583] [Info] Root: Loaded CodexDatabase in 0.00477803 seconds
[21:00:43.632] [Info] Root: Loaded BehaviorDatabase in 0.0493064 seconds
[21:00:43.634] [Info] Root: Loaded DanceDatabase in 0.00184971 seconds
[21:00:43.639] [Info] Root: Loaded SpawnTypeDatabase in 0.00480596 seconds
[21:00:43.643] [Info] Root: Loaded RadioMessageDatabase in 0.00363984 seconds
[21:00:46.172] [Info] Root: Loaded ItemDatabase in 3.57009 seconds
[21:00:55.522] [Info] UniverseServer: Acquiring universe lock file
[21:00:55.523] [Info] UniverseServer: Loading settings
[21:00:55.525] [Info] UniverseServer: Starting UniverseServer with UUID: 633546e21ac2db8c60291459f8a8a2ad
[21:00:55.536] [Info] UniverseServer: Logged in player '^red;Nox^reset;' locally
[21:00:55.536] [Info] UniverseServer: Logged in account '<anonymous>' as player '^red;Nox^reset;' from address local
[21:00:55.563] [Info] UniverseServer: Reviving player at ClientShipWorld:42b5bc4b18e15f6ac0965fbad29b03ae
[21:00:55.563] [Info] UniverseServer: Client '^red;Nox^reset;' <1> (local) connected
[21:00:55.568] [Info] UniverseClient: Joined server as client 1
[21:00:55.629] [Info] UniverseServer: Loading client ship world ClientShipWorld:42b5bc4b18e15f6ac0965fbad29b03ae
[21:00:56.131] [Info] UniverseServer: Warping player 1 to ClientShipWorld:42b5bc4b18e15f6ac0965fbad29b03ae=1005.63.1023.96
[21:00:57.148] [Info] Setting steam rich presence connection as steam id 76561198059291388
[21:00:57.338] [Error] Cannot set Steam achievement kill10poptops
[21:00:57.339] [Error] Cannot set Steam achievement trashpet
[21:00:57.339] [Error] Cannot set Steam achievement dismisscrewmember
[21:01:10.292] [Info] UniverseClient: Client disconnecting...
[21:01:10.399] [Info] Client received world stop packet, leaving: Removed
[21:01:10.530] [Info] UniverseServer: Client '^red;Nox^reset;' <1> (local) disconnected for reason: 
[21:01:10.530] [Info] UniverseServer: Stopping idle world ClientShipWorld:42b5bc4b18e15f6ac0965fbad29b03ae
[21:01:10.932] [Info] UniverseServer: Stopping UniverseServer
[21:01:10.947] [Info] Clearing steam rich presence connection
[21:01:14.146] [Info] Application: quit requested
[21:01:14.146] [Info] Application: quitting...
[21:01:14.146] [Info] Application: shutdown...
[21:01:14.375] [Info] Root: Shutting down Root
[21:01:14.653] [Info] Application: Destroying SDL Window
[21:01:14.660] [Info] Application: stopped gracefully
 [/spoiler]

**Comment by Fevix** [comment] 2016-08-23 02:06
Might not be from this mod. Will test soon

**Comment by Nox-Echo** [comment] 2016-08-23 02:07
spoiler tags dont work here? shame.

if you need me to run around on a monster infested planet for 5 mins i can do that too.

**Comment by Nox-Echo** [comment] 2016-08-23 02:12
a few of these mods are by me. godbikes makes the vanilla hoverbikes much tougher, jetspear lets rocketspear altability have much more thrust.

then theres the magnorb mod im working on. but i assure you ive had this problem before i added those in

**Comment by Fevix** [comment] 2016-08-23 10:40
Earth's Finest - Crew Improvements

You have a mod that's modifying the crew, so this is more likely to be the cause. If possible, remove this mod temporarily and see if the issue persists.

**Comment by Nox-Echo** [comment] 2016-08-23 20:08
i actually put that in because i thought it would fix my problem

**Comment by Nox-Echo** [comment] 2016-08-23 20:08
i removed it too and it changed pretty much nothing at all.

**Comment by Nox-Echo** [comment] 2016-08-23 20:10
ive even tried taking the crew ai from assets and making a mod from it and editing the agression and that still changed nothing

**Comment by Nox-Echo** [comment] 2016-08-24 11:31
sigh

**Comment by Nox-Echo** [comment] 2016-08-27 11:43
still nothing eh? even if it isnt your mod can you tell me how to force fix this

**Comment by Fevix** [comment] 2016-08-27 22:05
I don't know the cause of this, else I'd tell you.

**Comment by Fevix** [comment] 2017-07-06 22:01
This is coming up on a year old, and I never knew the root cause in the first place, so I'm going to close this issue.

**Closed by Fevix** 2017-07-06 22:01 UTC
