### ISSUE TITLE
Crash on startup with Avali (Triage) Race Mod installed

### ISSUE THREAD

**Issue by Bimbo-Bungus** [Avali-Triage-Team/Avali#430] opened 2020-07-31 03:50 UTC
When starting Starbound with the Avali (Triage) Race Mod installed, the game crashes on startup. Uninstalling the mod does fix the problem, but it shouldn't have to end like this. The same thing has happened with another race mod and this problem has only just showed up(a few days ago as of posting date), especially since I have had this mod installed for quite some time now, even with some playtime as an Avali. I suspect one of two things have happened: 1. Sayter's attempts to integrate Frackin Races into Frackin Universe may be making certain race mods unplayable. 2. Online modded playtime may have corrupted my game.

As per standard practice, the starbound.log is included.
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/5004946/starbound.log)

**Comment by Fevix** [comment] 2020-07-31 14:28
```[20:18:21.193] [Error] Application: exception thrown, shutting down: (StarException) Asset dependencies form a cycle```

There's some dependency loop in your mods. Avali Triage has an 'includes' for Frackin Universe because FU has Avali assets, and if FU loads after Avali, any changes I make to those assets will be negated.

This information may be slightly outdated, however. I'm checking with FU's owner.

**Comment by Kherae** [comment] 2020-08-09 07:27
ya forgot to close this issue now that the issue is resolved. (as of https://github.com/Avali-Triage-Team/Avali/commit/d7ff88addc3d29b1d7c2ad5a983459de5d78addf)
if you do change assets, leave a message on my patch mod's page, and i'll get 'em in.

**Closed** 2020-08-11 01:41 UTC
